// ============================================================
//  NutriCore — Catalogue de données produits
// ============================================================

const NUTRICORE_DATA = {

  categories: [
    { id: 'burners',    name: 'Brûleurs de graisse',  icon: '🔥', description: 'Formules thermogéniques avancées pour accélérer votre métabolisme.' },
    { id: 'drainants',  name: 'Drainants & Détox',    icon: '💧', description: 'Élimine les toxines et réduit la rétention d\'eau.' },
    { id: 'appetite',   name: 'Coupe-Faim',           icon: '🎯', description: 'Contrôlez vos envies et réduisez les fringales.' },
    { id: 'booster',    name: 'Boosters Énergie',     icon: '⚡', description: 'Maintien de l\'énergie tout au long de la journée.' },
  ],

  products: [
    // ── Brûleurs ───────────────────────────────────────────
    {
      id: 'thermofire-pro',
      category: 'burners',
      name: 'ThermoFire Pro',
      tagline: 'Le brûleur thermogénique #1',
      badge: 'Bestseller',
      badgeColor: '#FF4444',
      description: 'ThermoFire Pro est notre formule thermogénique la plus puissante. Combinant caféine anhydre, extrait de poivre noir (BioPerine®) et L-Carnitine, elle déclenche une combustion calorique intense tout en préservant la masse musculaire.',
      benefits: ['Accélère le métabolisme', 'Brûle les graisses tenaces', 'Augmente la thermogenèse', 'Conserve la masse maigre'],
      ingredients: 'Caféine anhydre 200mg, L-Carnitine Tartrate 500mg, Extrait de thé vert (50% EGCG) 300mg, BioPerine® 5mg, Vitamines B6 & B12.',
      usage: '2 gélules le matin à jeun ou 30 min avant l\'entraînement. Ne pas dépasser 4 gélules par jour.',
      rating: 4.8,
      reviews: 312,
      variants: [
        { id: 'tf-60',  label: '60 gélules',  subtitle: '1 mois',  price: 34.90, comparePrice: 44.90, stock: 47 },
        { id: 'tf-120', label: '120 gélules', subtitle: '2 mois',  price: 59.90, comparePrice: 79.90, stock: 23, popular: true },
        { id: 'tf-180', label: '180 gélules', subtitle: '3 mois',  price: 79.90, comparePrice: 109.90, stock: 12 },
      ],
      subscription: { available: true, discount: 15 },
      images: ['thermofire-pro'],
      tags: ['thermogénique', 'caféine', 'carnitine'],
    },
    {
      id: 'slimburn-elite',
      category: 'burners',
      name: 'SlimBurn Elite',
      tagline: 'Combustion 24h/24',
      badge: 'Nouveau',
      badgeColor: '#22C55E',
      description: 'SlimBurn Elite est conçu pour une combustion calorique continue, même au repos. Sa formule Day & Night libère ses actifs progressivement pour un effet brûle-graisse sur 24 heures.',
      benefits: ['Action jour et nuit', 'Sans nervosité', 'Formule sans stimulant', 'Idéal femmes et hommes'],
      ingredients: 'CLA (Acide Linoléique Conjugué) 1000mg, Extrait de safran 88,25mg, Raspberry Ketones 200mg, Forskoline 250mg, Chrome 200μg.',
      usage: '1 gélule matin et 1 gélule soir avec un grand verre d\'eau.',
      rating: 4.6,
      reviews: 187,
      variants: [
        { id: 'sb-60',  label: '60 gélules',  subtitle: '1 mois',  price: 29.90, comparePrice: 39.90, stock: 82 },
        { id: 'sb-120', label: '120 gélules', subtitle: '2 mois',  price: 49.90, comparePrice: 69.90, stock: 55, popular: true },
        { id: 'sb-180', label: '180 gélules', subtitle: '3 mois',  price: 69.90, comparePrice: 99.90, stock: 31 },
      ],
      subscription: { available: true, discount: 15 },
      images: ['slimburn-elite'],
      tags: ['CLA', 'sans caféine', 'nuit'],
    },
    {
      id: 'cutlean-max',
      category: 'burners',
      name: 'CutLean Max',
      tagline: 'Définition musculaire avancée',
      badge: 'Pro',
      badgeColor: '#F59E0B',
      description: 'Formulé pour les sportifs exigeants, CutLean Max combine puissants brûleurs et préservateurs musculaires. Idéal en phase de sèche pour révéler une silhouette sculptée.',
      benefits: ['Sèche musculaire', 'Préserve les muscles', 'Boost l\'énergie', 'Anti-catabolique'],
      ingredients: 'BCAA 2:1:1 2000mg, Acide hydroxycitrique (HCA) 500mg, Guarana 200mg, Zinc 10mg, Sélénium 55μg.',
      usage: '3 gélules par jour : 1 au réveil, 1 avant l\'entraînement, 1 le soir.',
      rating: 4.7,
      reviews: 94,
      variants: [
        { id: 'cl-90',  label: '90 gélules',  subtitle: '1 mois',  price: 39.90, comparePrice: 52.90, stock: 19 },
        { id: 'cl-180', label: '180 gélules', subtitle: '2 mois',  price: 69.90, comparePrice: 94.90, stock: 8, popular: true },
        { id: 'cl-270', label: '270 gélules', subtitle: '3 mois',  price: 94.90, comparePrice: 134.90, stock: 4 },
      ],
      subscription: { available: true, discount: 15 },
      images: ['cutlean-max'],
      tags: ['sèche', 'BCAA', 'sport'],
    },

    // ── Drainants ──────────────────────────────────────────
    {
      id: 'aquadetox-plus',
      category: 'drainants',
      name: 'AquaDetox Plus',
      tagline: 'Détox & Rétention d\'eau',
      badge: null,
      badgeColor: null,
      description: 'AquaDetox Plus est une formule complète pour éliminer les toxines accumulées et réduire la rétention d\'eau. Base de plantes médicinales certifiées biologiques.',
      benefits: ['Réduit la rétention d\'eau', 'Détoxifie le foie', 'Améliore le transit', 'Formule 100% végane'],
      ingredients: 'Pissenlit 500mg, Orthosiphon 300mg, Artichaut 250mg, Fenouil 200mg, Citrate de potassium 100mg.',
      usage: '2 comprimés matin et midi, avec un grand verre d\'eau. Cure de 4 semaines.',
      rating: 4.5,
      reviews: 143,
      variants: [
        { id: 'ad-60',  label: '60 comprimés', subtitle: '1 mois',  price: 24.90, comparePrice: 32.90, stock: 67 },
        { id: 'ad-120', label: '120 comprimés', subtitle: '2 mois', price: 42.90, comparePrice: 59.90, stock: 34, popular: true },
      ],
      subscription: { available: true, discount: 15 },
      images: ['aquadetox-plus'],
      tags: ['végane', 'détox', 'plantes'],
    },
    {
      id: 'drainfit-bio',
      category: 'drainants',
      name: 'DrainFit Bio',
      tagline: 'Drainage naturel certifié bio',
      badge: 'Bio',
      badgeColor: '#16A34A',
      description: 'DrainFit Bio est une tisane en gélules issue de l\'agriculture biologique certifiée. Une alternative douce et naturelle pour drainer et purifier l\'organisme.',
      benefits: ['Certifié biologique', 'Drainage doux', 'Soutient les reins', 'Sans additifs'],
      ingredients: 'Ortie bio 400mg, Reine des prés bio 200mg, Prêle bio 200mg, Pissenlit bio 150mg, Chiendent bio 100mg.',
      usage: '2 gélules matin et soir avec un grand verre d\'eau. À prendre pendant les repas.',
      rating: 4.4,
      reviews: 76,
      variants: [
        { id: 'df-60',  label: '60 gélules',  subtitle: '1 mois', price: 22.90, comparePrice: 28.90, stock: 93 },
        { id: 'df-120', label: '120 gélules', subtitle: '2 mois', price: 38.90, comparePrice: 52.90, stock: 51, popular: true },
      ],
      subscription: { available: true, discount: 15 },
      images: ['drainfit-bio'],
      tags: ['bio', 'plantes', 'doux'],
    },

    // ── Coupe-faim ─────────────────────────────────────────
    {
      id: 'satia-control',
      category: 'appetite',
      name: 'Satia Control',
      tagline: 'Satiété & Contrôle des envies',
      badge: null,
      badgeColor: null,
      description: 'Satia Control agit sur les mécanismes de la satiété pour vous aider à mieux contrôler vos apports caloriques. Riche en fibres solubles naturelles et en chrome.',
      benefits: ['Prolonge la satiété', 'Réduit les fringales', 'Stabilise la glycémie', 'Sans excitants'],
      ingredients: 'Glucomannane (Konjac) 2000mg, Psyllium blond 500mg, Chrome 200μg, Extrait de Gymnema 200mg.',
      usage: '2 gélules avec un grand verre d\'eau (300ml) 30 minutes avant les 2 principaux repas.',
      rating: 4.6,
      reviews: 218,
      variants: [
        { id: 'sc-120', label: '120 gélules', subtitle: '1 mois',  price: 27.90, comparePrice: 35.90, stock: 112 },
        { id: 'sc-240', label: '240 gélules', subtitle: '2 mois',  price: 47.90, comparePrice: 65.90, stock: 67, popular: true },
      ],
      subscription: { available: true, discount: 15 },
      images: ['satia-control'],
      tags: ['konjac', 'fibres', 'satiété'],
    },

    // ── Boosters ───────────────────────────────────────────
    {
      id: 'energyx-daily',
      category: 'booster',
      name: 'EnergyX Daily',
      tagline: 'Énergie & Focus toute la journée',
      badge: null,
      badgeColor: null,
      description: 'EnergyX Daily combine adaptogènes et vitamines du groupe B pour soutenir votre niveau d\'énergie et votre concentration tout au long de la journée, sans pic ni crash.',
      benefits: ['Énergie soutenue', 'Améliore la concentration', 'Réduit la fatigue', 'Anti-stress naturel'],
      ingredients: 'Ashwagandha KSM-66® 600mg, Rhodiola Rosea 300mg, Coenzyme Q10 100mg, Vitamines B1 B2 B3 B5 B6 B12.',
      usage: '2 gélules le matin avec le petit-déjeuner.',
      rating: 4.9,
      reviews: 425,
      variants: [
        { id: 'ex-60',  label: '60 gélules',  subtitle: '1 mois',  price: 32.90, comparePrice: 42.90, stock: 88 },
        { id: 'ex-120', label: '120 gélules', subtitle: '2 mois',  price: 55.90, comparePrice: 74.90, stock: 43, popular: true },
        { id: 'ex-180', label: '180 gélules', subtitle: '3 mois',  price: 74.90, comparePrice: 104.90, stock: 21 },
      ],
      subscription: { available: true, discount: 15 },
      images: ['energyx-daily'],
      tags: ['adaptogène', 'ashwagandha', 'focus'],
    },
    {
      id: 'nightburn-advanced',
      category: 'burners',
      name: 'NightBurn Advanced',
      tagline: 'Brûle les graisses pendant le sommeil',
      badge: 'Top Vente',
      badgeColor: '#8B5CF6',
      description: 'NightBurn Advanced est une formule nocturne unique qui optimise la combustion des graisses pendant le sommeil tout en améliorant sa qualité. Sans stimulant, sans insomnie.',
      benefits: ['Actif la nuit', 'Améliore le sommeil', 'Sans caféine', 'Optimise la récupération'],
      ingredients: 'CLA 1000mg, Mélatonine 1mg, L-Tryptophane 500mg, Magnésium marin 300mg, Lemon Balm 200mg.',
      usage: '2 gélules 30 minutes avant le coucher. Ne pas dépasser 2 gélules par prise.',
      rating: 4.7,
      reviews: 267,
      variants: [
        { id: 'nb-60',  label: '60 gélules',  subtitle: '1 mois',  price: 31.90, comparePrice: 41.90, stock: 58 },
        { id: 'nb-120', label: '120 gélules', subtitle: '2 mois',  price: 54.90, comparePrice: 72.90, stock: 29, popular: true },
      ],
      subscription: { available: true, discount: 15 },
      images: ['nightburn-advanced'],
      tags: ['nuit', 'sommeil', 'mélatonine'],
    },
  ],

  testimonials: [
    { name: 'Sophie M.',  location: 'Lyon',   rating: 5, text: 'ThermoFire Pro m\'a aidée à perdre 6kg en 2 mois combiné à une alimentation saine. Vraiment bluffant !', product: 'ThermoFire Pro', avatar: 'SM' },
    { name: 'Thomas R.', location: 'Paris',  rating: 5, text: 'EnergyX Daily a transformé mes matinées. Je me lève avec de l\'énergie et je reste focus toute la journée.', product: 'EnergyX Daily', avatar: 'TR' },
    { name: 'Camille L.', location: 'Bordeaux', rating: 4, text: 'Satia Control m\'aide à ne plus grignoter entre les repas. C\'est exactement ce qu\'il me fallait !', product: 'Satia Control', avatar: 'CL' },
    { name: 'Julien F.',  location: 'Nantes', rating: 5, text: 'CutLean Max pendant ma préparation : j\'ai affiné ma silhouette tout en gardant mes muscles. Parfait.', product: 'CutLean Max', avatar: 'JF' },
    { name: 'Marie-Pierre B.', location: 'Toulouse', rating: 5, text: 'NightBurn Advanced m\'a réconciliée avec le sommeil ET m\'a aidée à affiner ma silhouette. Double effet !', product: 'NightBurn Advanced', avatar: 'MB' },
    { name: 'Alex D.', location: 'Strasbourg', rating: 4, text: 'SlimBurn Elite est doux et efficace. Aucune nervosité, juste des résultats progressifs et durables.', product: 'SlimBurn Elite', avatar: 'AD' },
  ],
};
